services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    container_name: at-terrace-frontend
    volumes:
      - ./src/frontend:/app
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    ports:
      - "${IP}:3000:3000"
    tty: true
