FROM node:latest
RUN yarn add @mui/material @emotion/react @emotion/styled
RUN yarn add styled-components
RUN yarn add @mui/icons-material
# ARG UID=1000
# RUN useradd -m -u ${UID} h_kinjo
# USER ${UID}
WORKDIR /app